###########################
### Home Assistant Core ###
###########################

frontend:       # enables frontend
  themes: !include config/themes.yaml
  
config:         # enables configurations panel
map:            # enables map panel
history:        # enables history panel
logbook:        # enables logbook panel
system_health:  # enables system health monitoring

lovelace:       # enables lovelace in yaml-mode
  mode: yaml



################
### INCLUDES ###
################

automation: !include_dir_merge_list automation/
binary_sensor: !include config/binary_sensor.yaml
group: !include groups/groups.yaml
input_datetime: !include config/input_datetime.yaml
light: !include groups/lights.yaml
script: !include_dir_merge_named scripts/
zone: !include config/zones.yaml



##################
### COMPONENTS ###
##################

# Cloud
cloud:

# Device tracker
device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 10
    consider_home: 900
    new_device_defaults:
      track_new_devices: false
      hide_if_away: true

# Google Home
# googlehome:
#   devices:
#     - host: !secret bedroom_display_host
#       track_alarms: true
#       track_devices: false

# Nissan Leaf
nissan_leaf:
  username: !secret username
  password: !secret car_password
  region: NE
  update_interval:
    hours: 1
  update_interval_charging:
    hours: 1
  update_interval_climate:
    minutes: 5
  force_miles: false

# Sensor
sensor:
  # Time and date
  - platform: time_date
    display_options:
      - 'time'

  # Weather
  - platform: yr

# Spotify
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# Sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Tibber
tibber:
  access_token: !secret tibber_access_token

# Vacuum
vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_host
    token: !secret vacuum_token
    name: Oda

# Weather
weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily