# Vacuum weekday routine time
vacuum_time:
  has_date: false
  has_time: true
  initial: '10:00'

# Weekday alarm time
weekday_alarm_time:
  has_date: false
  has_time: true
  initial: '06:30'

# Weekend alarm time
weekend_alarm_time:
  has_date: false
  has_time: true
  initial: '10:00'