# weekday alarm
- alias: 'Weekday alarm'
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.weekday_alarm_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.all_users
      state: 'home'
  action:
    - service: light.turn_on
      entity_id:
        - light.bedroom_left
        - light.bedroom_right
      data:
        transition: 600
        brightness: 255
    - service: script.turn_on
      entity_id: script.sonos_group_all
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room
        - media_player.second_bedroom
        - media_player.bathroom
      data:
        volume_level: 0.15
    - service: media_player.select_source
      entity_id: media_player.second_bedroom
      data:
        source: "NRK P3"
    - service: media_player.media_play
      entity_id: media_player.second_bedroom

# weekend alarm
- alias: 'Weekend alarm'
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.weekend_alarm_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: group.all_users
      state: 'home'
  action:
    - service: light.turn_on
      entity_id:
        - light.bedroom_left
        - light.bedroom_right
      data:
        transition: 600
        brightness: 255
    - service: script.turn_on
      entity_id: script.sonos_group_all
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room
        - media_player.second_bedroom
        - media_player.bathroom
      data:
        volume_level: 0.15
    - service: media_player.select_source
      entity_id: media_player.second_bedroom
      data:
        source: "NRK P3"
    - service: media_player.media_play
      entity_id: media_player.second_bedroom