# coming home routine
- alias: 'Entering home'
  trigger:
    platform: state
    entity_id: group.all_users
    from: 'not_home'
    to: 'home'
  action:
    - service: light.turn_on
      entity_id:
        - light.entrance_panel
        - light.living_room_lights
    - service: script.turn_on
      entity_id: script.sonos_group_all
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room
        - media_player.second_bedroom
        - media_player.bathroom
      data:
        volume_level: 0.15
    - service: media_player.select_source
      entity_id: media_player.second_bedroom
      data:
        source: "Soft Pop Hits"
    - service: media_player.media_play
      entity_id: media_player.second_bedroom

# leaving home routine
- alias: 'Leaving home'
  trigger:
    platform: state
    entity_id: group.all_users
    from: 'home'
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: script.turn_on
      entity_id: script.sonos_group_all
    - service: media_player.media_pause
      entity_id: media_player.second_bedroom