# bedtime routine
- alias: 'Bedtime trigger'
  trigger:
    platform: state
    entity_id: light.bedroom_lights
    from: 'on'
    to: 'off'
  condition:
    - condition: time
      after: '22:00:00'
      before: '05:00:00'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: state
      entity_id: input_boolean.phone_plugged_in
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.bedtime_routine

# coming home routine
- alias: 'Entering home'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: light.turn_on
      entity_id:
        - light.panel_entrance
        - light.living_room_lights
    - service: script.turn_on
      entity_id: script.sonos_group_all
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room
        - media_player.bedroom
        - media_player.bathroom
      data:
        volume_level: 0.15
    - service: media_player.select_source
      entity_id: media_player.bedroom
      data:
        source: "Soft Pop Hits"
    - service: media_player.media_play
      entity_id: media_player.bedroom

# leaving home routine
- alias: 'Leaving home'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: script.turn_on
      entity_id: script.sonos_group_all
    - service: media_player.media_pause
      entity_id: media_player.bedroom